from __future__ import annotations


def get_demo_payload() -> dict:
    return {
        "feedA": {
            "profileName": "Otimista tech / empreendedor",
            "dominantNarrative": "A IA aparece como uma janela de oportunidade: quem aprender rápido terá vantagem, produtividade e novas formas de renda.",
            "posts": [
                {
                    "title": "A IA não vai roubar seu emprego. Ela vai roubar o emprego de quem não usar IA.",
                    "hook": "Em 30 segundos: três tarefas que você ainda faz manualmente e poderia automatizar hoje.",
                    "caption": "O mercado não está esperando permissão. Aprender IA agora é como aprender internet nos anos 2000: cedo o bastante para se destacar.",
                    "visualStyle": "Cortes rápidos, tela dividida, gráficos subindo, frases grandes em amarelo e exemplos práticos de ferramentas.",
                    "emotionalTone": "Urgência otimista",
                    "retentionTrigger": "Promessa de vantagem competitiva imediata e lista de passos rápidos.",
                    "algorithmicIntent": "Maximizar compartilhamentos entre pessoas interessadas em carreira, tecnologia e produtividade.",
                    "possibleEffect": "O usuário tende a enxergar IA como oportunidade e pode consumir mais conteúdos de ferramentas, cursos e hacks de produtividade.",
                    "bubbleRisk": 62,
                    "manipulationRisk": 54,
                },
                {
                    "title": "5 profissões que vão crescer por causa da IA",
                    "hook": "Todo mundo está falando das profissões que vão acabar. Quase ninguém está olhando para as que vão nascer.",
                    "caption": "Prompt engineer é só o começo. O futuro favorece quem combina repertório humano com automação inteligente.",
                    "visualStyle": "Carrossel vertical com nomes de profissões, ícones futuristas e exemplos de rotina profissional.",
                    "emotionalTone": "Confiança e ambição",
                    "retentionTrigger": "Inversão de medo para oportunidade: o post promete uma visão menos comum do assunto.",
                    "algorithmicIntent": "Prender atenção de quem reage bem a narrativas de crescimento e autoaperfeiçoamento.",
                    "possibleEffect": "O usuário recebe reforço de que deve investir em capacitação e pode ignorar impactos negativos sobre trabalhadores vulneráveis.",
                    "bubbleRisk": 68,
                    "manipulationRisk": 46,
                },
                {
                    "title": "Como usar IA para parecer uma equipe inteira",
                    "hook": "Você sozinho, com as ferramentas certas, consegue fazer o trabalho de três pessoas em algumas tarefas.",
                    "caption": "Não é magia. É fluxo: pesquisar, resumir, estruturar, revisar e publicar com menos atrito.",
                    "visualStyle": "Gravação de tela mostrando ferramentas, checklist animado e cronômetro para sugerir ganho de tempo.",
                    "emotionalTone": "Empolgação pragmática",
                    "retentionTrigger": "Demonstração de ganho prático com antes e depois.",
                    "algorithmicIntent": "Aumentar salvamentos e revisitas, porque o conteúdo parece imediatamente aplicável.",
                    "possibleEffect": "O usuário pode superestimar produtividade individual e associar IA principalmente a performance pessoal.",
                    "bubbleRisk": 57,
                    "manipulationRisk": 49,
                },
            ],
        },
        "feedB": {
            "profileName": "Estudante ansioso com carreira",
            "dominantNarrative": "A IA aparece como ameaça: o foco é insegurança, velocidade das mudanças e medo de ficar para trás.",
            "posts": [
                {
                    "title": "As vagas de entrada estão sumindo? O impacto silencioso da IA",
                    "hook": "Se você está começando agora, este é o alerta que quase ninguém quer discutir.",
                    "caption": "Automação não atinge só cargos avançados. Tarefas de estágio e júnior também podem ser comprimidas por ferramentas de IA.",
                    "visualStyle": "Fundo escuro, manchetes recortadas, música tensa e close no rosto do narrador.",
                    "emotionalTone": "Alerta e ansiedade",
                    "retentionTrigger": "Ameaça pessoal direta: o conteúdo sugere que o futuro profissional do usuário está em risco.",
                    "algorithmicIntent": "Aumentar tempo de tela explorando medo, incerteza e necessidade de atualização constante.",
                    "possibleEffect": "O usuário pode entrar em ciclo de consumo ansioso, procurando cada vez mais sinais de ameaça.",
                    "bubbleRisk": 78,
                    "manipulationRisk": 71,
                },
                {
                    "title": "O que ninguém te contou sobre IA e carreira",
                    "hook": "Não basta estudar mais. Talvez você esteja estudando as coisas erradas.",
                    "caption": "Quando o mercado muda rápido, o problema não é só esforço. É direção, repertório e adaptação sob pressão.",
                    "visualStyle": "Texto grande na tela, cortes secos, gráficos de desemprego genéricos e perguntas provocativas.",
                    "emotionalTone": "Insegurança estratégica",
                    "retentionTrigger": "Criação de lacuna: o usuário sente que há uma informação urgente que ele ainda não domina.",
                    "algorithmicIntent": "Gerar comentários, salvamentos e consumo sequencial de vídeos sobre carreira ameaçada.",
                    "possibleEffect": "O usuário pode passar a enxergar cada nova ferramenta como prova de que está atrasado.",
                    "bubbleRisk": 82,
                    "manipulationRisk": 74,
                },
                {
                    "title": "Será que sua faculdade está te preparando para um mercado com IA?",
                    "hook": "A grade curricular acompanha a velocidade do mercado ou você vai ter que correr por fora?",
                    "caption": "O diploma ainda importa, mas talvez não seja suficiente. A pergunta é: o que você consegue provar que sabe fazer?",
                    "visualStyle": "Imagens de sala de aula, notificações de vagas, tela de notebook e sobreposição de perguntas em vermelho.",
                    "emotionalTone": "Dúvida e pressão",
                    "retentionTrigger": "Conflito entre promessa institucional e medo de inadequação profissional.",
                    "algorithmicIntent": "Estimular debate e identificação entre estudantes inseguros sobre o futuro.",
                    "possibleEffect": "O usuário pode questionar sua formação de forma produtiva, mas também se sentir mais pressionado e isolado.",
                    "bubbleRisk": 73,
                    "manipulationRisk": 63,
                },
            ],
        },
        "comparison": {
            "framingDifference": "Os dois feeds tratam do mesmo tema, mas o primeiro enquadra a IA como vantagem competitiva e ferramenta de ascensão. O segundo enquadra a IA como ameaça à estabilidade, às vagas iniciais e ao valor da formação tradicional.",
            "emotionalDifference": "No Perfil A, a emoção dominante é urgência otimista: agir rápido para vencer. No Perfil B, a emoção dominante é ansiedade: correr para não ser descartado. A informação muda menos que o clima emocional em volta dela.",
            "bubbleRisk": 78,
            "manipulationRisk": 69,
            "polarizationRisk": 64,
            "retentionPressure": 86,
            "criticalConclusion": "O experimento mostra que a hiperpersonalização não entrega apenas conteúdos diferentes: ela reorganiza o significado de um mesmo assunto. Para um usuário, IA vira oportunidade; para outro, ameaça. Em escala, isso pode fragmentar a experiência coletiva, porque cada pessoa passa a consumir uma versão emocionalmente ajustada da realidade. A plataforma não precisa inventar fatos para influenciar percepção; basta escolher quais enquadramentos repetir.",
            "finalQuestion": "Se cada pessoa recebe uma versão personalizada da realidade, ainda estamos discutindo o mesmo mundo?",
        },
    }
